### ISSUE TITLE
Add built-in convention transformations

### ISSUE THREAD

**Issue by henkmollema** [henkmollema/Dapper-FluentMap#10]

**Comment by zakwillis** [comment]
Hi there, I just wrote a regular expression for handling this. Most Oracle databases, tends to have upper case and underscore separators as a naming convention, and most POCO developers in C# tends to use Pascal casing.
Oracle = COLUMN_NAME
POCO = ColumnName
The convention regular expression that I added was as follows.

Regex.Replace(s, @"(?ms-inx:((?<=.{1})(.{1})(?=[A-Z])))", @"$+_").ToUpper()

**Comment by henkmollema** [comment]
There is already an example in the readme: https://github.com/henkmollema/Dapper-FluentMap#transformations.

It basically does the same, except for the upper casing. That is fixed by added `.ToUpper()` after the `Transform()` method.

**Comment by zakwillis** [comment]
Hi again, with the Microsoft.Net implementation of regular expressions, it is better to put the options inside the regular expression than to rely on doing this inside the C# Regex options. I use a really good free tool for building regular expressions called Expresso, it even handles the substitution pieces. The regular expression provided ignores the first character, and then finds the character before any single capital letters in the POCO and replaces it with an underscore. Anyway, thanks again for writing this extension to Dapper.
