### ISSUE TITLE
How to handle multiple mappings to same model?

### ISSUE THREAD

**Issue by bokmadsen** [henkmollema/Dapper-FluentMap#113]
Can Dapper-FluentMap handle mutiple mappings to same model? I have a model I use for 2-3 different requests, and I can't garantie same column names each time:
Request1 (col1, col2, col3) -> Model (prop1, prop2, prop3)
Request2 (col2, col3, col3) -> Model (prop1, prop2, prop3)

From what I can read, this won't be possible, because the EntityMapper only takes the destination (Model) as type.

I there a way to work around this?

**Comment by mxmissile** [comment]
I ran into this today, can't get it to work either.  Unforfunate.

**Comment by henkmollema** [comment]
Unfortunately this is not supported. You'll have to create distinct models.
