### ISSUE TITLE
Could not load type 'IColumnNameResolver' from assembly Dommel, Version=2.0.0.0

### ISSUE THREAD

**Issue by gkurbesov** [henkmollema/Dapper-FluentMap#117]
i'm using Dapper.FluentMap and i see exception when call FluentMapper for Dommel.

```C#
using Dapper.FluentMap;
using Dapper.FluentMap.Dommel;

...

 public void FluentMapperInit()
        {
            FluentMapper.Initialize(config =>
            {
                config.AddMap(new Email.MailDataMap());

                config.AddMap(new Fcm.FcmDataMap());
                config.AddMap(new Fcm.FcmHookMap());

                config.AddMap(new Telegram.TelegramDataMap());
                config.AddMap(new Telegram.TelegramHookMap());

                config.ForDommel(); // this show exception
            });
        }
```

> System.TypeLoadException: "Could not load type 'IColumnNameResolver' from assembly 'Dommel, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'."

![image](https://user-images.githubusercontent.com/39064929/84752904-08403600-afc7-11ea-884b-cfedd3f95932.png)

my nugets:

![image](https://user-images.githubusercontent.com/39064929/84753141-4d646800-afc7-11ea-8db0-bf106328ab38.png)

**Comment by igordibuccio** [comment]
I have this same problem. Can anyone help?

**Comment by TroySchmidt** [comment]
https://github.com/henkmollema/Dapper-FluentMap/pull/105
I submitted a pull request months ago to resolve the issue since a major revision has breaking changes for the dependency.  It hasn't been approved and now v2 is official.

**Comment by nullpainter** [comment]
Hi @henkmollema , can you indicate why this issue was closed? Is there a way to use Dapper.FluentMap with Dommel 2, or should we consider Dapper.FluentMap to no longer be supported with Dommel?

**Comment by henkmollema** [comment]
Because there is a PR by @TroySchmidt which fixes this issue.

**Comment by gkurbesov** [comment]
@henkmollema , @TroySchmidt? But it still doesn't work. I updated all dependencies and it also throws an exception

**Comment by guipcarvalho** [comment]
I'm having the same issue here

**Comment by IainCoSource** [comment]
{"Could not load type 'IColumnNameResolver' from assembly 'Dommel, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'.":"IColumnNameResolver"}
![image](https://user-images.githubusercontent.com/49510009/99540889-cc1b6200-29b8-11eb-85bb-546fa5e0fe60.png)

Came across this issue today
