### ISSUE TITLE
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

### ISSUE THREAD

**Issue by drma-dev** [henkmollema/Dapper-FluentMap#127]
```
public class BadgeMapper : EntityMap<BadgeVM>
    {
        public BadgeMapper()
        {
            Map(p => p.Rank.Level)
                .ToColumn("Rank_Level");
        }
    }
```

As in my previous ticket, I tried with just one mapping to see if it worked, but it is generating another error.

**Comment by henkmollema** [comment]
Do you have a full stack trace?

**Comment by drma-dev** [comment]
There is no stacktrace, as it is an exception generated by the visual studio itself. But this is easy to reproduce, because I believe that the component is not recognizing attributes of another class

**Comment by jgador** [comment]
I encountered this error when I have nested types in my mapping for CustomPropertyTypeMap.
