### ISSUE TITLE
Dapper.FluentMap.Dommel nuget package is not updated since 8/23/2020

### ISSUE THREAD

**Issue by ahmedsafan86** [henkmollema/Dapper-FluentMap#132]
https://www.nuget.org/packages/Dapper.FluentMap.Dommel/
![image](https://user-images.githubusercontent.com/6296474/124838947-238e3280-df88-11eb-8f44-ae29c1f16548.png)

[PR 129](https://github.com/henkmollema/Dapper-FluentMap/pull/129) contains a critical fix, @henkmollema can you please update it?.

**Comment by jkuek** [comment]
I first came across Dommel today and don't use it in production, but it seems to me that the new builds are now just called Dommel rather than Dapper.FluentMap.Dommel

https://github.com/henkmollema/Dommel

The latest version at the time of writing is 2.3.3

**Comment by PavelFischerCoupa** [comment]
@jkuek, dommel and fluent map are different projects.
@ahmedsafan86 any news about new release?

**Comment by henkmollema** [comment]
I'm archiving this repository as I'm not using this library myself anymore and have no time maintaining it. Thanks for using it.
