### ISSUE TITLE
Ignore() exception

### ISSUE THREAD

**Issue by DanieleSky** [henkmollema/Dapper-FluentMap#133]
Hi,
when a property is marked with "ignore()" the Select throw an exception "Not implemented exception"
![image](https://user-images.githubusercontent.com/11925650/142888815-d04b064b-9353-455b-94ca-89b3bb877c4a.png)

This is the mapping
![image](https://user-images.githubusercontent.com/11925650/142888965-e027579a-7813-4ea1-80c0-04316b3f4173.png)

**Comment by lndr27** [comment]
Same problem here. Waiting for the PR #131 to be approved.

**Comment by henkmollema** [comment]
I'm archiving this repository as I'm not using this library myself anymore and have no time maintaining it. Thanks for using it.
