### ISSUE TITLE
not working map fields To ValueObject 

### ISSUE THREAD

**Issue by mohammad-markazi** [henkmollema/Dapper-FluentMap#134]
hello I Trying To map fields to ValueObject But Not Working 

![Capture](https://user-images.githubusercontent.com/92588311/227803734-9349ad30-34f0-4e83-ae26-236cf16c63f3.PNG)

**Comment by henkmollema** [comment]
I'm archiving this repository as I'm not using this library myself anymore and have no time maintaining it. Thanks for using it.
