### ISSUE TITLE
Transformations are case sensitive

### ISSUE THREAD

**Issue by Gimmeaphatbeat** [henkmollema/Dapper-FluentMap#20]
In the Transformations example... if the database column is lower case, like "hello_world", and the POCO is HelloWorld, the property is never populated.

However if the database column is "Hello_World" then it works.

Is this to be expected? If so, what is the solution to be able to map a POCO property HelloWorld to hello_world column?

**Comment by Gimmeaphatbeat** [comment]
(I'm referring to the regex transformations example in the readme)

**Comment by henkmollema** [comment]
You can just call `ToLower()` after `Regex.Replace()`:

```csharp
c.Transform(s => Regex.Replace(s, "([A-Z])([A-Z][a-z])|([a-z0-9])([A-Z])", "$1$3_$2$4").ToLower());
```

**Comment by Gimmeaphatbeat** [comment]
Thanks, that's excellent. I guess if you specify lowercase it becomes case insenstive?

This probably isn't the right place to ask this question, but is it possible to map a POCO to *either* underscore *or* CamelCase? So the POCO would be CamelCase, and the database column could be camel_case or CamelCase, and Dapper would map to either one.

**Comment by henkmollema** [comment]
It's not really case-insensitive as it will try to find an exact match for `"hello_world"`. I guess I have to look into this (and create some tests too).

As for the multiple column name mappings: this is currently not supported, but think it's a a nice feature.

**Comment by henkmollema** [comment]
Multiple conventions issue: #21

**Comment by Gimmeaphatbeat** [comment]
Actually this seems to be the behavior of it, using the regex example. 

So a POCO property HelloWorld already maps to db columns:
-hello_world
-Hello_World
-helloworld

**Comment by tablesaw** [comment]
Dapper supports mapping ignoring underscores and case. Just add this:

`Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;`

(Commenting here because I landed on this page in my search to figure it out.)
