### ISSUE TITLE
Mapping fails on inherited properties

### ISSUE THREAD

**Issue by fichtenelch75** [henkmollema/Dapper-FluentMap#29]
I noticed that inherited properties are not mapped by fluent mapper. Debugging led me to line 45 in the file "src\Dapper.FluentMap\TypeMaps\FluentConventionTypeMap.cs"

Changing

    .Where(map => map.PropertyInfo.DeclaringType == type &&

to

    .Where(map => map.PropertyInfo.ReflectedType == type &&

fixes the problem

**Comment by henkmollema** [comment]
@fichtenelch75  could you provide a repro sample of your derived entities and the convention?

**Comment by henkmollema** [comment]
This is the same issue as mentioned in #24. Completely forgot about it. I'll commit a fix soon.

**Comment by splattne** [comment]
Could you please deploy this fix as a new version of the library and update the NuGet package as well? That would be aewsome. Thanks!
