### ISSUE TITLE
Port to .NET Core

### ISSUE THREAD

**Issue by henkmollema** [henkmollema/Dapper-FluentMap#33]
Port the application to DNX.

**Comment by Gonkers** [comment]
:+1: I like the sounds of this. Thanks for putting it on your list.

```The dependency Dapper.FluentMap 1.4.0 does not support framework .NETPlatform,Version=v5.4.```

**Comment by henkmollema** [comment]
@Gonkers I've started working the v2 in the [corresponding branch](https://github.com/HenkMollema/Dapper-FluentMap/tree/v2). However I've ran into an issue where `DefaultTypeMap` was not public anymore. This issue have been [fixed](https://github.com/StackExchange/dapper-dot-net/commit/9feabe5632ead36b5b03a01df121f8ecfc30d0be) and I will continue working on it.

**Comment by henkmollema** [comment]
@Gonkers I've uploaded a first beta version of v2: https://www.nuget.org/packages/Dapper.FluentMap/2.0.0-beta-1

There is a known bug with mapping properties from derived types, but most of the other functionality should work.

**Comment by Gonkers** [comment]
So far it looks good. Thanks!

**Comment by henkmollema** [comment]
.NET Core RTM package pushed to NuGet: https://www.nuget.org/packages/Dapper.FluentMap/1.5.1
