### ISSUE TITLE
1.5.* fails with Dapper multi mapping where 1.4.1 works

### ISSUE THREAD

**Issue by cpisto** [henkmollema/Dapper-FluentMap#42]
On .net 4.5.2 (Dapper 1.50.2), Dapper.FluentMap 1.5.0 and 1.5.1 using the PropertyTransformConvention from the readme applied via:

```
FluentMapper.Initialize(config =>
{
    config.AddConvention<PropertyTransformConvention>()
          .ForEntitiesInCurrentAssembly("App.Domain.Models")
}
```

in conjunction with Dapper multi mapping throws an exception:

> Finding mappings for column 'id' yielded more than 1 PropertyMap. The conventions should be more specific.

Works perfectly with 1.4.1 and below.

**Comment by henkmollema** [comment]
That's odd. Nothing should have changed there. Does your entity and database table still looks the same?

**Comment by cpisto** [comment]
Yes everything is the same, swapping 1.5.* for 1.4.1 fixes the issue.

In my example, both tables have an id column, however only one of the entities being multi-mapped has a matching Id property.

I will try to find time to build a specific test case later this week.

**Comment by bengavin** [comment]
We are seeing a similar issue when moving to 1.5.1 from 1.4.x, in our case, it seems to be directly related to inheritance hierarchies.  When we register a global property prefix, we're seeing the duplicate property map error showing up.  Commenting out the ForEntity<> for the derived classes (or base class) makes the problem go away, but prevents the conventions from apply to those excluded entities.

**Comment by henkmollema** [comment]
This have been fixed for applications targeting full .NET (e.g. 4.5 or higher) and .NET Core 2.0 and 2.1 in version 1.7.0: [NuGet](https://www.nuget.org/packages/Dapper.FluentMap/1.7.0) and [release notes](https://github.com/henkmollema/Dapper-FluentMap/releases/tag/v1.7.0).

Please re-open or create a new issue if the problem persists.
