### ISSUE TITLE
how to map nested class 

### ISSUE THREAD

**Issue by schild** [henkmollema/Dapper-FluentMap#45]
i try to create mapper like

``` csharp
public class WordsMap : EntityMap<Words>
{

}
```

the class Words have a property which is a list object,
i found I cannot mapper it ,and maybe i  need use `where(p=>p.perpertyName).tocolumn("alias")`?

**Comment by henkmollema** [comment]
I'm not sure what you're asking. Please elaborate on what you are trying to do. If this is still an issue, feel free to re-open it.
