### ISSUE TITLE
'Invalid column name' error for ignored columns during UpdateAsync()

### ISSUE THREAD

**Issue by yohanmishkin** [henkmollema/Dapper-FluentMap#49]
I'm executing `UpdateAsync()` on a really basic object having also added a map that ignores 3 columns, but I'm still getting the `invalid column name` error. `FluentMapper.Initialize` was called beforehand and I see the mapping when calling Dapper's `SqlMapper.GetTypeMap()`. Any ideas?

**Comment by henkmollema** [comment]
What is `UpdateAsync()`? That's not part of this library.

**Comment by yohanmishkin** [comment]
`UpdateAsync()` is a Dapper.Contrib method. I didn't realize FluentMap doesn't work with Contrib. Apologies.
