### ISSUE TITLE
Multiple properties with same column name causes exception

### ISSUE THREAD

**Issue by henkmollema** [henkmollema/Dapper-FluentMap#5]
For example these models:

```
public class Product
{
    public int Id { get; set; }
}

public class Order
{
    public int Id { get; set; }
}
```

With this convention:

```
public class PrefixConvention : Convention
{
    public PrefixConvention()
    {
        Properties<int>()
            .Where(p => p.Name.ToLower() == "id")
            .Configure(config => config.HasColumnName("autID");
    }
}
```

Causes an exception which tells you that duplicate mappings are found for the column `autID` since it finds the `PropertyMap` instance for `Order` and `Product`. A check for the property type should be added to the filter predicate.

**Comment by kaanacar34** [comment]
public class TypePrefixConvention:Convention
    {
        public TypePrefixConvention()
        {
           
            Properties<int>()
                .Where(c => c.Name == "Id" )
                .Configure(c => c.HasColumnName("BrandId"));

            Properties<int>()
                .Where(c => c.Name == "Id")
                .Configure(c => c.HasColumnName("CategoryId"));

        }

    }


I want it to match the Id for both categoryId and BrandId.

example:
FluentMapper.Initialize(config=>config.AddConvention<TypePrefixConvention>().ForEntity<Brand>().ForEntity<Category>());

**Comment by kaanacar34** [comment]
My Entities ; 

 public class Category
    {
        public int Id  { get; set; }
        public string Name  { get; set; }
        public string Definition  { get; set; }
        public int ParentId  { get; set; }

    }

  public class Brand
    {   
        public int Id  { get; set; }
        public string Name  { get; set; }
        public string Definition { get; set; }
    }


 {
        public int Id { get; set; }
      //  public int UnitId  { get; set; }
        public Unit Unit  { get; set; }
       // public int CategoryId  { get; set; }
        public Category Category  { get; set; }
       // public int BrandId  { get; set; }
        public Brand Brand  { get; set; }
        public string Name  { get; set; }
        public string Definition  { get; set; }
    }

**Comment by kaanacar34** [comment]
Sql Query;

Select p.Id, p.Name, p.Definition,
                    p.UnitId, u.Name, u.Definition,
                    p.CategoryId, c.Name, c.Definition,
                    p.BrandId, b.Name, b.Definition 
                    FROM Products p 
                    LEFT join Units u ON p.UnitId = u.Id 
                    LEFT JOIN Categories c ON c.Id = p.CategoryId 
                    LEFT JOIN Brands b ON b.Id = p.BrandId
