### ISSUE TITLE
Strong named assembly

### ISSUE THREAD

**Issue by shubhapillai** [henkmollema/Dapper-FluentMap#52]
Hello
I am experiencing difficulty using the library within a strong named assembly for it not being signed. I had the same issue with Dapper but with the new version of Dapper.Strongname I overcame it. But the FluentMap library does not seem to provide a version that works with the strong named Dapper. Would it be possible to get one in place?

Thanks and Regards
Shubha

**Comment by henkmollema** [comment]
@shubhapillai perhaps [StrongNamer](https://www.nuget.org/packages/StrongNamer/) works for you?
