### ISSUE TITLE
Unable to map entity to insert and update

### ISSUE THREAD

**Issue by riguelbf** [henkmollema/Dapper-FluentMap#53]
```cs
public class InventoryMovementTypeMap : DommelEntityMap<InventoryMovementType>
    {
        public InventoryMovementTypeMap()
        {
            ToTable("inventory_movement_types");
            Map(i => InventoryMovementTypeId).ToColumn("InventoryMovementTypeID").IsKey().IsIdentity();
            Map(i => i.Action).ToColumn("Action", caseSensitive: false);
            Map(i => i.Code).ToColumn("Code", caseSensitive: false);
            Map(i => i.Name).ToColumn("Name", caseSensitive: false);

        }
    }
```

```cs
public class RegisterMappings
    {
        public static void Register()
        {
            FluentMapper.Initialize(config =>
            {
                config.AddMap(new InventoryMovementTypeMap());
                config.ForDommel();
            });
        }
    }
```

It's correct??

**Comment by henkmollema** [comment]
That seems correct, yes. What is the problem here?

**Comment by riguelbf** [comment]
trying save and update data in store the library don't mapping class object to ansi query

this is result  query building by library : 
`set nocount on insert into inventory_movement_types () values () select cast(scope_identity() as int)`

is not building table fields and values

**Comment by henkmollema** [comment]
That seems like a Dommel issue. What package versions are you using. And are you using SQL Server?

**Comment by riguelbf** [comment]
I'm using lastest package version(1.4.5) Dapper.FluentMapper.Dommel and Sql Server 2008/R2

**Comment by riguelbf** [comment]
`    string sql;
            if (!_insertQueryCache.TryGetValue(type, out sql))
            {
                var tableName = Resolvers.Table(type);

                bool isIdentity;
                var keyProperty = Resolvers.KeyProperty(type, out isIdentity);

                var typeProperties = new List<PropertyInfo>();
                foreach (var typeProperty in Resolvers.Properties(type))
                {
                    if (typeProperty == keyProperty)
                    {
                        if (isIdentity)
                        {
                            // Skip key properties marked as an identity column.
                            continue;
                        }
                    }

                    // Why all properties must had set method public? <-
                    if (typeProperty.GetSetMethod() != null) // <------------------------ issue its here
                    {
                        typeProperties.Add(typeProperty);
                    }
                }

                var columnNames = typeProperties.Select(Resolvers.Column).ToArray();
                var paramNames = typeProperties.Select(p => "@" + p.Name).ToArray();

                var builder = GetBuilder(connection);
                sql = builder.BuildInsert(tableName, columnNames, paramNames, keyProperty);

                _insertQueryCache.TryAdd(type, sql);
            }

            return sql;
        }`

**Comment by henkmollema** [comment]
I see, Dommel (Dapper actually) needs a public setter on a property to write values back to it. It doesn't make a lot of sense with an insert operation though. Are you able to add public setters to your properties?

**Comment by riguelbf** [comment]
on my logic is not idea, but dapper required i go rewrite my implementation . Thanks for help me

**Comment by henkmollema** [comment]
All right, good luck!

**Comment by riguelbf** [comment]
Thank's and congratulation by project!
