### ISSUE TITLE
Is there a way to insert a POCO without Dommel?

### ISSUE THREAD

**Issue by orenht** [henkmollema/Dapper-FluentMap#55]
I couldn't find a way.

Thanks

**Comment by henkmollema** [comment]
What do you mean, "without Dommel"? The only thing Dapper.FluentMap does for you is create a mapping betwoon POCO properties and column names. It does not generate any query, that's what Dommel does for you.

**Comment by orenht** [comment]
Yeah, I meant how do you write the query after the mapping, because I didn't see documentation about it.

**Comment by henkmollema** [comment]
I'm still not sure what you're asking. Please re-open the issue if you think this is still an issue and you can elaborate on it.
