### ISSUE TITLE
Exception when mapping an inherited property in a derived object

### ISSUE THREAD

**Issue by orenht** [henkmollema/Dapper-FluentMap#56]
Hi,

I have a type B that inherits from type A, and a Property P defined in A.
When I try to map that property in type B, an exception is thrown at the DommelColumnNameResolver, that the key is not present in the entity maps dictionary.

I suggest that instead of using the DeclaringType for the lookup, use the ReflectedType.

Maybe this issue exists in other places too, I haven't checked.

**Comment by henkmollema** [comment]
That is indeed a known issue. However, [`ReflectedType`](https://apisof.net/catalog/System.Type.ReflectedType) is not available in .NET Standard 1.3 (which Dapper.FluentMap and Dommel) targets. A future version might target .NET Standerd 2.0 which allows us to use `RefelectedType` again.

**Comment by henkmollema** [comment]
This have been fixed for applications targeting full .NET (e.g. 4.5 or higher) and .NET Core 2.0 and 2.1 in version 1.7.0: [NuGet](https://www.nuget.org/packages/Dapper.FluentMap/1.7.0) and [release notes](https://github.com/henkmollema/Dapper-FluentMap/releases/tag/v1.7.0).

Dapper.FluentMap.Dommel is updated as well: https://www.nuget.org/packages/Dapper.FluentMap.Dommel/1.6.0.

Please re-open or create a new issue if the problem persists.
