### ISSUE TITLE
Dapper.FluentMap v2

### ISSUE THREAD

**Issue by henkmollema** [henkmollema/Dapper-FluentMap#62]
v2 of Dapper.FluentMap will bring several new features and bugfixes while maintaining a simple API.

### Improved configuration
- More flexibility
- Inline mapping builder (separate classes are still supported as well)
- Better testability
- Easier transformation convention setup

### Remove use of `ReflectedType` and `DeclaringType`
`ReflectedType` is inconsistent and is not available on .NET Standard 1.3. Providing different implementations according to the target framework seems like a bad idea. The best way to solve this is to not use `ReflectedType` at all and get a hold on a reference to the object.

Related issues:
- #42 
- #43 
- #56 

### Incorporate more mappings into Dommel
Dommel does not use all available mappings provided by Dapper.FluentMap. Make use of the extensibility points of Dommel and use the mapping configuration of Dapper.FluentMap.

Related issues:
- #57

## Todo
- [x] Implement manual mapping with improved configuration
- [x] Implement Dommel extension
- [ ] Implement conventions

## Preview versions
- [2.0.0-beta1](https://www.nuget.org/packages/Dapper.FluentMap/2.0.0-beta1) :shipit: 
  - Manual entity mapping
  - Dommel support
  - No convention support
- 2.0.0-beta2
  - Bugfixes from beta1
  - Conventions support

<hr>

Any more suggestions are welcome! 🎉

**Comment by nicolastakashi** [comment]
It would be very good if we had the possibility to perform a mapping of 1 -> N

Initially, It could be could only follow first-level mapping.

For example

````
    public class Profile
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IEnumerable<Profile> Type { get; set; }
    }`

**Comment by nicolastakashi** [comment]
I opened a one-to-many mapping issue #63  that I think would be great if we had it available in this next release.

**Comment by henkmollema** [comment]
[Dapper.FluentMap 2.0.0-beta1](https://www.nuget.org/packages/Dapper.FluentMap/2.0.0-beta1) is just shipped.

**Comment by henkmollema** [comment]
I'm archiving this repository as I'm not using this library myself anymore and have no time maintaining it. Thanks for using it.
