### ISSUE TITLE
Mapping one to many

### ISSUE THREAD

**Issue by nicolastakashi** [henkmollema/Dapper-FluentMap#63]
It would be very good if we had the possibility to perform a mapping of 1 -> N

Initially, It could be could only follow first-level mapping.

For example

````
    public class Profile
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IEnumerable<Profile> Type { get; set; }
    }`

**Comment by jr-araujo** [comment]
It would be awesome whether this feature was implemented in Dapper.FluentMap. Why? It's so bad when you've an one-to-many situation and, using actual Dapper or Dapper.FluentMap - you're obligated to manually implement the fulfill a 'N' data collection from one-to-many relationship.

So, this feature will be GREAT handful, whether this is implemented.

**Comment by henkmollema** [comment]
Please help me understand. Why won't this work when you define a mapping for `User and `Profile`?

**Comment by jr-araujo** [comment]
@henkmollema What I mean is when you have a situation where the database mapping is one-to-many, like this:

**Order** and  **OrderItem**, right? (I won't explicit all properties to keep easy the explanation), that is mean that you need to map one-to-many using a mapping mechanism from **Dapper.FluentMap**, right? (_I'm not sure if this feature really exists there_)

If you try to configure this mapping using **Dapper.FluentMap**, I think that isn't possible and you won't manage do that mapping work as well, with Dapper.FluentMap, to get one-to-many mapping working so good.

Therefore, I would like to know, if you've interest in implements this feature in Dapper.FluentMap, 'cause if you've intention to implement it, It will be much handy for us.

**Comment by henkmollema** [comment]
@jr-araujo I see, but Dapper.FluentMap does not really know or care about relational mappings (one-to-many for example). The mapping logic of Dapper just hands FluentMap a type and a column name and want a property on that type in return.

So if you correctly configure the individual mappings for say, `Order` and `OrderItem`, I expect it to just work. What FluentMap _doesn't_ do is, assign a list of `OrderItems` to the `Order` instance, you should do that manually using [multi-mapping](https://github.com/StackExchange/Dapper/#multi-mapping) when you call `connection.Query()`.

**Comment by JMFURY** [comment]
I am about to use Dommel and FluentMap to accomplish this. I'll post a gist for others to reference once I have it working. 

These libraries are a lifesaver by the way. Much appreciated

**Comment by henkmollema** [comment]
@nicolastakashi please re-open if you think this is still relevant.
