### ISSUE TITLE
Make a dotnet core2 compatible version

### ISSUE THREAD

**Issue by Savij** [henkmollema/Dapper-FluentMap#66]
Love this mapping for dapper, but I need a version that will work with dotnet core 2. Please enter as an enhancement.

**Comment by henkmollema** [comment]
It is already compatible with .NET Core 2.0 as it targets .NET Standard 1.3. Does something not work for you?

**Comment by Savij** [comment]
When I added it to Visual Studio from NuGet it added dependencies to .net framework 4.6.2 (I think that was the version). Is there some other way to add it? I am using VS on the mac, so it could be wonky....

**Comment by henkmollema** [comment]
That's odd. Try executing this in your project folder:
```
dotnet add package Dapper.FluentMap
```

**Comment by Savij** [comment]
Dude! I apologize! I must have clicked on the one above it in the nuget browser. My bad, its all good! Thanks for getting back to me!

**Comment by henkmollema** [comment]
You're welcome!
