### ISSUE TITLE
Does Dommel FluentMap support Sequence?

### ISSUE THREAD

**Issue by gustavozafra** [henkmollema/Dapper-FluentMap#69]
I need to specify that the ID is generated by a sequence in Oracle I would need something like the example below. It's possible?
`Map(x => x.Id).IsKey().IsSequence("SEQUENCE_NAME").ToColumn("ID_ERCA");`

**Comment by henkmollema** [comment]
No, this is not possible. Sequences are not supported in all database provides Dapper.FluentMap and/or Dommel supports.
