### ISSUE TITLE
Create a Strong Name package version

### ISSUE THREAD

**Issue by akasexdev** [henkmollema/Dapper-FluentMap#73]
Can you please create a strong name version of this package? So it can be easily used with Dapper.StrongName package.

Thank you!

**Comment by henkmollema** [comment]
The regular Dapper package (which we depend on) is not strong named. Using the Dapper.StrongNamed package could break application dependency trees. Therefore I can't strong name the Dapper.FluentMap package. I also won't create a second strong named NuGet package as that's against [the strong naming guidelines](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming).

Dapper will probably strong name it's package in v2.0, after that Dapper.FluentMap can be strong named as well.
