### ISSUE TITLE
Support Multiple keys

### ISSUE THREAD

**Issue by andreaLeo** [henkmollema/Dapper-FluentMap#74]
Hello Henk,

And thanks for the amazing job, i'm using your libraries now on my current project.
I was wondering if you planned to support multiple keys in your mapper ?

Regards

https://github.com/henkmollema/Dapper-FluentMap/blob/6fc00177b0fb3ecabed4e886b8e8af3bec698333/src/Dapper.FluentMap.Dommel/Resolvers/DommelKeyPropertyResolver.cs#L45

**Comment by lucaxchaves** [comment]
Can i take this issue?

**Comment by henkmollema** [comment]
This will be fixed by #105.
