### ISSUE TITLE
Protected property

### ISSUE THREAD

**Issue by diegodfsd** [henkmollema/Dapper-FluentMap#76]
This is the first time I'm trying to use dapper-fluentmap v2 and I would like to have the set protected in my model classes but now it is not possible.

**Comment by henkmollema** [comment]
It's not possible for classes outside the class hierarchy to set protected properties. What are you trying to achieve?

**Comment by henkmollema** [comment]
Do you have an example of which protected properties you are trying to set?

**Comment by diegodfsd** [comment]
I would like to have my class definition like that:
```
public class Device: Statusable<Device>, IAggregateRoot
{
        public string Name { get; protected set; }
        public string Description { get; protected set; }
        public string Ip { get; protected set; }
        public int Port { get; protected set; }

        protected Device()
        {
        }

       public Device(string name, string description, string ip, int port) 
       {
           Name = name;
           Description = description;
           Ip = ip;
           Port = port;
       }

```

**Comment by henkmollema** [comment]
And which part is not working with that class definition?
