### ISSUE TITLE
Combining Convention and EntityMap

### ISSUE THREAD

**Issue by JonasHansen16** [henkmollema/Dapper-FluentMap#77]
First of all a quick thank you for all the work you've put into this project.

Currently i'm trying to combine conventions and an entitymap to map a poco to one of my db tables.
The convention covers most of the database column names, however most of our primary keys have the same name. This obviously causes issues when working with joins.
Is it possible to let my convention handle the mapping for certain columns and using an entitymap to handle the other columns my convention can't?

So far i haven't been able to make it work, it seems to either take one or the other.

**Comment by henkmollema** [comment]
Currently this does not work out of this box. You might try this:

Add this class:
```cs
public class CombinedTypeMap<TEntity> : MultiTypeMap
{
    public CombinedTypeMap() 
        : base(new FluentConventionTypeMap<TEntity>(), new MultiTypeMap<TEntity>())
    {
    }
}
```

Then register a Dapper type map for each of your entity (after you called `FluentMapper.Initialize(...)`):

```cs
SqlMapper.SetTypeMap(typeof(Foo), new CombinedTypeMap<Foo>());
// do this for all your entities
```

**Comment by blai30** [comment]
Any update on this? I would love to define one `Convention` and zero entity mappers then have Dommel automatically map my PascalCase POCO properties to my snake_case MySQL columns/tables

**Comment by henkmollema** [comment]
I'm archiving this repository as I'm not using this library myself anymore and have no time maintaining it. Thanks for using it.
