### ISSUE TITLE
Doesn't seem to map for Dapper-1.50.5 / Dapper.Contrib-1.50.5

### ISSUE THREAD

**Issue by chriswolf-nrg** [henkmollema/Dapper-FluentMap#78]
I have an entity which looks like:
```
[Dapper.Contrib.Extensions.Table("Correspondence")]
public class Correspondence : ICloneable
{
    public Correspondence()
    {
    }
    // other properties are name-for-name identical to db column names.
    [Column("bcc_archived_at")]
    public DateTime? BccArchivedAt { get; set; }
}
```
The database column is named "bcc_archived_at".  I have a custom mapping class, like so:

Custom mapping class:
```
    internal class CorrespondenceMap : EntityMap<Correspondence>
    {
        internal CorrespondenceMap()
        {
            Map(c => c.BccArchivedAt).ToColumn("bcc_archived_at");
        }
    }
```
FluentMap initialization before any other code:
```
FluentMapper.Initialize(config =>
{
    config.AddMap<Correspondence>(new CorrespondenceMap());
});
```
`Dapper.Contrib` connection extension code for insert called like so:
```
using (var conn = ConnectionFactory.GetConnection(Dsn))
{
    Correspondence c = new Correspondence()
    {
        BccArchivedAt = DateTime.Now
    };
    long id = conn.Insert<Correspondence>(c);
}
```

This insert call throws:
```
System.Data.SqlClient.SqlException: 'Invalid column name 'BccArchivedAt'.'
```
Is FluentMap supposed to work with `Dapper.Contrib` extensions?

**Comment by henkmollema** [comment]
> Is FluentMap supposed to work with Dapper.Contrib extensions?

Nope, it does not work with Dapper.Contrib. Shameless plug: it does work together with [Dommel](https://github.com/henkmollema/Dommel) using the `Dapper.FluentMap.Dommel` integration component.

**Comment by tariq-n-ahmad** [comment]
Was this ever fixed in Dapper?
