### ISSUE TITLE
Dispose Mappings

### ISSUE THREAD

**Issue by adiii4** [henkmollema/Dapper-FluentMap#79]
`System.InvalidOperationException: 'Adding entity map for type 'XXX' failed. The type already exists. Current entity maps: XXX`

I currently execute the method `FluentMapper.Initialize(config => { ... });` inside a `UnitOfWork` class which I add as a Transient Service in ASP.NET Core.

Is there some way to dispose the mappings inside of my `UnitOfWork` class?

**Comment by adiii4** [comment]
Currently I check if there are already any `EntityMaps` or `TypeConventions` before I call `FluentMapper.Initialize()`

```csharp
if(FluentMapper.EntityMaps.Count <= 0 && FluentMapper.TypeConventions.Count <= 0)
{
   FluentMapper.Initialize(config => { 
      //... 
   });
}
```

Nevertheless, I think it would be useful if you could dispose the mappings and type conventions manually or is there a drawback I don't see?

**Comment by henkmollema** [comment]
`FluentMapper.Initialize` is meant to be called at application startup. I suggest you invoke it once somewhere in the `Program` or `Startup` class of your application.

**Comment by adiii4** [comment]
This would also possible. As I want to keep my current architecture (persistence layer), I will keep it like this.

Although I would love to have the feature for disposing any `EntityMaps` or `TypeConventions` as it could be useful for example when you would like to encapsulate the persistence layer from other layers.

**Comment by adiii4** [comment]
Your first solution fits perfectly for my case! Thank you for that. I totally didn't see those methods. I implemented them when my UoW disposes and it works 👍

Yes I think we could argue about and it is probably a smart idea, in my opinion, as you don't have to think about clearing the entity and convention collections.

**Comment by henkmollema** [comment]
Great, glad it works out.

I guess clearing the configuration on each call to `Initialize` might be a little too disturbing. People could rely on it being additive. Perhaps a new method like `ClearConfiguration` makes more sense and is more easily discovered.

Anyways, I'm closing this out.

**Comment by acoskun** [comment]
Hi. I added this code to my data class constructor.  This is work for me.

if (!FluentMapper.EntityMaps.Keys.Contains(typeof(**<YourType>**)) && !FluentMapper.TypeConventions.Keys.Contains(typeof(**<YourType>**)))
            {
                FluentMapper.Initialize(config => {
                    //... 
                });
            }


<img width="800" alt="ekran resmi 2018-12-08 10 43 12" src="https://user-images.githubusercontent.com/9384992/49683438-237add00-fad6-11e8-89c4-f3417cfa6736.png">
