### ISSUE TITLE
Need instance initialization for Integration tests in ASP.NET Core to be working

### ISSUE THREAD

**Issue by dsokhach** [henkmollema/Dapper-FluentMap#84]
I'm writing integration tests in ASP.NET Core projects, like described here: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2.
Calling [CreateClient();](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.testing.webapplicationfactory-1.createclient?view=aspnetcore-2.2) start application in memory. And single instance of application is OK, however when you have **>1 test** the exception is being thrown:
`Message: System.InvalidOperationException : Adding entity map for type 'my type here' failed. The type already exists. Current entity maps: 'list of already registered types', which obviously contains the entity being added for 2nd time.
`

Similar issue I faced year ago with AutoMapper static initialized, and they have instance based initialization: http://docs.automapper.org/en/stable/Static-and-Instance-API.html through dependency injection using `IServiceCollection services`, calling `services.AddAutoMapper(configuration => configuration.AddProfiles(typeof(<some type from my assembly>));`.

My guess that here FluentMap should have instance based initialization as well.

**Comment by hyphmongo** [comment]
As a quick fix you might be able to clear the mappings before initialize

`FluentMapper.EntityMaps.Clear();`

**Comment by dsokhach** [comment]
@hyphmongo  thank you for pointing this. I had the same approach initially with automapper. It indeed helps until there are about less than 4-6 tests (probably depends on how many core running machine has). However if there more it will break random test.

**Comment by henkmollema** [comment]
Dapper.FluentMap is a different case than AutoMapper. Dapper.FluentMap sets up a type map for Dapper which cannot be done via DI. Whereas with AutoMapper you consume the mappings yourself when you inject `IMapper` in your code. I don't see a way how to use Dapper.FluentMap concurrently, I usually disable parallel test execution in that case.
