### ISSUE TITLE
Trouble with ToTable() method

### ISSUE THREAD

**Issue by zadykian** [henkmollema/Dapper-FluentMap#90]
Hi, Henk!
I've found that there are two interfaces with same names:
Dapper.Dommel.FluentMapping.IDommelEntityMap
Dapper.FluentMap.Dommel.Mapping.IDommelEntityMap
It caused a problem when I tried to specify table name via ToTable("tableName") method:
```
public class DommelTableNameResolver : DommelMapper.ITableNameResolver
{
    public string ResolveTableName(Type type)
    {
        IEntityMap entityMap;
        if (FluentMapper.EntityMaps.TryGetValue(type, out entityMap))
        {
            IDommelEntityMap dommelEntityMap = entityMap as IDommelEntityMap;
            if (dommelEntityMap != null)
                return dommelEntityMap.TableName;
        }
        return DommelMapper.Resolvers.Default.TableNameResolver.ResolveTableName(type);
    }
}
```
Here is a save cast of client's DommelEntityMap to Dapper.FluentMap.Dommel.Mapping.IDommelEntityMap, but base class DommelEntityMap<TEntity> implements Dapper.Dommel.FluentMapping.IDommelEntityMap,
so default table resolver is used in any case. 
I had to explicitly implement both DommelEntityMap<TEntity> and Dapper.FluentMap.Dommel.Mapping.IDommelEntityMap interface to deal with this problem.
I use Dapper.Dommel 2.0.0.1 and Dapper.FluentMap.Dommel 1.7.0.

P.S.
Thank you a lot for you work!

**Comment by TroySchmidt** [comment]
How did you resolve using this?  I am having the same issue when trying to use version 2 of Dommel.

**Comment by zadykian** [comment]
> How did you resolve using this? I am having the same issue when trying to use version 2 of Dommel.
As I said, I had to explicitly implement both DommelEntityMap and Dapper.FluentMap.Dommel.Mapping.IDommelEntityMap interfaces.

**Comment by henkmollema** [comment]
`Dapper.Dommel` is a different package (not mine). That's why those interfaces are incompatible.

Also, `Dapper.FluentMap` / `Dapper.FluentMap.Dommel` (which are mine) are not yet compatible with Dommel 2.0.

**Comment by TroySchmidt** [comment]
I upgraded Dapper.FluentMap.Dommel to be compatible and will be submitting a PR for it.
