### ISSUE TITLE
Property name transform configuration not working

### ISSUE THREAD

**Issue by grandsilence** [henkmollema/Dapper-FluentMap#91]
Hi. I'm trying to convert `MyCustomProperty` to `my_custom_property` column (snake case) globally (for Postgresql). But `Convention` not applying to my model or even assembly namespaces.

Initialization:
```csharp
public class Startup
{
        public void ConfigureServices(IServiceCollection services)
        {
           FluentMapper.Initialize(config => {
                config.AddConvention<PropertyTransformConvention>()
                    .ForEntity<Bot>();

                // manual mapping working fine
                // config.AddMap(new BotMap());
                config.ForDommel();
            });
        }
}
```

My `Convention`:
```csharp
public class PropertyTransformConvention : Convention
    {
        public PropertyTransformConvention()
        {
            Properties()
                .Configure(c => c.Transform(s => s.ToSnakeCase()));
        }
    }
```
**ToSnakeCase()** working well.

Result SQL:
```sql
insert into Bots (Token, Login, Enabled, Comment, TemplateStart) values (@Token, @Login, @Enabled, @Comment, @TemplateStart) RETURNING Id
```
Expected SQL:
```sql
insert into Bots (token, login, enabled, comment, template_start) values (@Token, @Login, @Enabled, @Comment, @TemplateStart) RETURNING id
```

`PropertyTransformConvention` constructor called but column names stays unchanged.
Thank you.

**Comment by henkmollema** [comment]
My guess is that mixing manual mapping and conventions does not work. Can you try it without configuring the manual mapped?

**Comment by grandsilence** [comment]
Without manual mapped it has the same behavior

**Comment by jonathanschein** [comment]
Hi,

Is not possible to configure convention mapping and then override only one property for a model?

Thanks!

**Comment by StefanJanssen95** [comment]
I have the same issue, did you have any luck solving it?

The project it is in is open source and I pushed it in the state with the error so it can be looked at:
https://github.com/StefanJanssen95/steam-web-api-wrapper/tree/2fe3d1c16d9cc9b12477f3d251a16dd4fc53d4e4

**Comment by StefanJanssen95** [comment]
I found out why my code was not working. For retrieving data I used my own SQL function which was executed by Dapper itself. For updating I was using the Dapper.Contrib function which does not use the configured column names.

**Comment by henkmollema** [comment]
This should be fixed in https://www.nuget.org/packages/Dapper.FluentMap.Dommel/1.7.1.
