### ISSUE TITLE
ReadOnly Fields

### ISSUE THREAD

**Issue by azilberbaum** [henkmollema/Dapper-FluentMap#94]
Would love to have a ReadOnly property like there is for Ignore

**Comment by henkmollema** [comment]
I don't think I understand. What are you trying to achieve?

**Comment by azilberbaum** [comment]
Basically I want to add a field I can populate in my model via a query but not have it try to save to the database.

Example could be a computed field, or a count field.

If I use ignore it won’t populate, so really need read only property.

This would be huge for me!

**Comment by StefanJanssen95** [comment]
If I understand the feature suggestion correctly another use would be for a ``Created`` field. It will get a default value from the database when inserting and you don't want to keep supplying it for every update.

**Comment by TroySchmidt** [comment]
@azilberbaum  I have been able to accomplish this with public get and private set on the accessibility of the model property.  The behavior I experience is the property is populated on the selects and ignored on the insert and updates.  (i.e. computed fields)

**Comment by henkmollema** [comment]
Not sure what to do here. Please re-open if you have an example of desired behavior (or a PR! :-))
